import React from 'react';
import { Prompt } from 'react-router-dom';
import { FieldGroup } from 'react-reactive-form';
import { bool, object } from 'prop-types';
import { connect } from 'react-redux';
import get from 'lodash/get';
import ExportInline from './ExportInline';
import PreferencesFormWrapper from './PreferencesFormWrapperN';
import VersionController from '../../batteries/components/shared/VersionController';
import Banner from '../../batteries/components/shared/UpgradePlan/Banner';
import Overlay from '../../components/Overlay';

const bannerMessages = {
	free: {
		title: 'Code Editor',
		description:
			'GUI to edit your saved search configuration inline in a sandpack editor. Sandpack provides a live preview of the current code - starting with the code generated by the UI Builder search configuration',
		buttonText: 'Read Docs',
		icon: 'info-circle',
		href: 'https://docs.reactivesearch.io/docs/reactivesearch/ui-builder/search/#edit-code-inline',
	},
};

const CodeSandboxModal = ({ ...props }) => {
	const preferenceId = props.match.params.id;

	const closeForm = () => {
		props.history.push('/cluster/search-builder');
	};

	return (
		<React.Fragment>
			<Prompt message="Are you sure you want to leave?" />

			<div>
				{props.isPaidUser ? (
					<VersionController version="8.1.0">
						<PreferencesFormWrapper closeForm={closeForm} preferenceId={preferenceId}>
							{/* eslint-disable-next-line */}
							{({ getPreferences, getPreferencesPayload, form }) => {
								return (
									<FieldGroup
										control={form}
										render={() => (
											<ExportInline
												preferences={getPreferencesPayload()}
												buttonProps={{
													style: {
														marginLeft: 10,
													},
												}}
												control={form}
												closeForm={closeForm}
												preferenceId={preferenceId}
												getPreferencesPayload={getPreferencesPayload}
											/>
										)}
									/>
								);
							}}
						</PreferencesFormWrapper>
					</VersionController>
				) : (
					<React.Fragment>
						<Banner {...bannerMessages.free} />
						<Overlay
							style={{
								maxWidth: '70%',
							}}
							src="https://i.imgur.com/igSOMzm.png"
							alt="Code Editor"
						/>
					</React.Fragment>
				)}
			</div>
		</React.Fragment>
	);
};

CodeSandboxModal.propTypes = {
	history: object.isRequired,
	match: object.isRequired,
	isPaidUser: bool.isRequired,
};

const mapStateToProps = (state) => ({
	isPaidUser: get(state, '$getAppPlan.results.isPaid'),
});

export default connect(mapStateToProps)(CodeSandboxModal);
